- name: add docker group to user
  become: yes
  user:
    name: frezbo
    append: yes
    groups:
      - docker

- name: create docker daemon json
  become: yes
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker
