- name: add docker group to user
  become: yes
  user:
    name: frezbo
    append: yes
    groups:
      - docker

- name: create docker daemon json
  become: yes
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: install docker fish completion
  get_url:
    url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/fish/docker.fish
    dest: "/home/{{ user }}/.config/fish/completions/docker.fish"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: create buildkit config folder
  file:
    path: "/home/{{ user }}/.config/buildkitd"
    state: directory
    mode: 0755
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: create buildkit config
  template:
    src: buildkitd.toml.j2
    dest: "/home/{{ user }}/.config/buildkitd/buildkitd.toml"
    owner: "{{ user }}"
    group: "{{ user }}"
