- name: manage bashrc
  blockinfile:
    path: "/home/{{ user }}/.bashrc"
    content: ". /home/{{ user }}/.config/dotfiles/bashrc"

- name: manage user profile
  blockinfile:
    path: "/home/{{ user }}/.profile"
    content: ". /home/{{ user }}/.config/dotfiles/profile"

- name: Create chezmoi state directory
  file:
    path: "/home/{{ user }}/.local/share/chezmoi"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Create chezmoi config directory
  file:
    path: "/home/{{ user }}/.config/chezmoi"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Check if chezmoi is configured
  stat:
    path: "/home/{{ user }}/.local/share/chezmoi/README.md"
  register: chezmoi_exists

- name: Clone dotfiles repo
  git:
    repo: https://github.com/frezbo/dotfiles.git
    dest: "/home/{{ user }}/.local/share/chezmoi"
  when:
    - not chezmoi_exists.stat.exists

- name: Create chezmoi config file
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - url: https://raw.githubusercontent.com/frezbo/dotfiles/main/dot_config/chezmoi/chezmoi.toml
      dest: "/home/{{ user }}/.config/chezmoi/chezmoi.toml"
  when:
    - not chezmoi_exists.stat.exists
