- name: Add apt-keys
  become: yes
  apt_key:
    url: "{{ item.key | default(omit) }}"
    state: present
    keyserver: "{{ item.keyserver | default(omit) }}"
    id: "{{ item.keyid | default(omit) }}"
  with_items: "{{ packages }}"

- name: Add package repositories
  become: yes
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.repo_file_name | default(item.package) }}"
    update_cache: yes
  with_items: "{{ packages }}"

- name: Install packages
  become: yes
  apt:
    name: "{{ packages | map(attribute='package') | list }}"
    state: latest
    update_cache: yes
