- name: "Get gnome extension version"
  command:
    argv:
      - gnome-extensions
      - version
  register: gnome_version_info
  run_once: true

- name: "Get Gnome Shell extensions info"
  uri:
    url: https://extensions.gnome.org/extension-info/?pk={{ item }}&shell_version={{ gnome_version_info.stdout }}
    return_content: true
  register: gnome_extension_info
  with_items: "{{ extension_ids }}"

- name: "Gnome extensions directory"
  file:
    path: "/home/{{ user }}/.local/share/gnome-shell/extensions/{{ item.json.uuid }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items: "{{ gnome_extension_info.results }}"

- name: "Unzip Gnome extensions"
  unarchive:
    src: "https://extensions.gnome.org{{ item.json.download_url }}"
    dest: "/home/{{ user }}/.local/share/gnome-shell/extensions/{{ item.json.uuid }}"
    creates: "/home/{{ user }}/.local/share/gnome-shell/extensions/{{ item.json.uuid }}/metadata.json"
    remote_src: yes
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items: "{{ gnome_extension_info.results }}"
