- name: "Install external packages"
  vars:
    packages:
      - package: "kicad"
        repo: "deb https://ppa.launchpadcontent.net/kicad/kicad-6.0-releases/ubuntu/ jammy main"
        keyid: "245D5502FAD7A805"
        keyserver: "keyserver.ubuntu.com"
      - package: tailscale
        repo: "deb https://pkgs.tailscale.com/stable/ubuntu jammy main"
        key: "https://pkgs.tailscale.com/stable/ubuntu/jammy.gpg"
      - package: code
        repo_file_name: vscode
        repo: "deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main"
        key: "https://packages.microsoft.com/keys/microsoft.asc"
      - package: docker-ce
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
        key: "https://download.docker.com/linux/ubuntu/gpg"
  include_tasks: external-packages.yml

- name: common packages
  become: yes
  apt:
    name:
      - tilix
      - fish
      - fonts-firacode
      - xclip
      - kazam
      - vim
      - tree
      - picocom
      # gpg
      - scdaemon
      # fingerprint
      - libpam-fprintd
      # tlp
      - tlp
      - acpi-call-dkms
      - ffmpeg
      # docker
      - docker-ce-cli
      - containerd.io
      # qemu
      - qemu
      - qemu-system
      - qemu-user-static
      # cross-compile
      - gcc-aarch64-linux-gnu
      - g++-aarch64-linux-gnu
      - binutils-aarch64-linux-gnu
      # dev stuff
      - libxml2-utils
      # world time
      - gnome-clocks
      - pax-utils
      - ipmitool
      - rpi-imager
    state: latest
    update_cache: yes

- name: setup tlp
  include_tasks: tlp.yml

- name: setup flatpaks
  vars:
    packages:
      - com.discordapp.Discord
      - com.slack.Slack
      - im.riot.Riot
      - md.obsidian.Obsidian
      - org.chromium.Chromium
      - org.flameshot.Flameshot
      - org.gnome.Calls
      - us.zoom.Zoom
      - md.obsidian.Obsidian
  include_tasks: flatpak.yml

- name: Setup dotfiles
  include_tasks: dotfiles.yml

- name: Setup Gnome extensions
  vars:
    extension_ids:
      - 4839 # gnome-clipboard-history
      - 7 # removable drive menu
      - 906 # audio switcher
  include_tasks: gnome.yml

- name: Setup docker
  include_tasks: docker.yml

- name: gsettings
  gsetting:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: org.gnome.desktop.interface.clock-format
      value: "'24h'"
    - key: org.gnome.desktop.interface.clock-show-seconds
      value: "true"
    - key: org.gnome.desktop.interface.clock-show-weekday
      value: "true"
    - key: org.gnome.desktop.interface.show-battery-percentage
      value: "true"
    - key: org.gnome.desktop.peripherals.mouse.natural-scroll
      value: "true"
    - key: org.gnome.desktop.peripherals.mouse.speed
      value: "1.0"
    - key: org.gnome.desktop.peripherals.touchpad.natural-scroll
      value: "true"
    - key: org.gnome.desktop.peripherals.touchpad.speed
      value: "1.0"
    - key: org.gnome.desktop.peripherals.touchpad.two-finger-scrolling-enabled
      value: "true"
    - key: org.gnome.system.location.enabled
      value: "false"
    - key: org.gnome.settings-daemon.plugins.power.power-button-action
      value: "'suspend'"
    - key: org.gnome.settings-daemon.plugins.power.sleep-inactive-ac-timeout
      value: "1800"
    - key: org.gnome.settings-daemon.plugins.power.sleep-inactive-ac-type
      value: "'nothing'"
    - key: org.gnome.settings-daemon.plugins.power.sleep-inactive-battery-timeout
      value: "900"
    - key: org.gnome.settings-daemon.plugins.power.sleep-inactive-battery-type
      value: "'suspend'"
    - key: org.gnome.shell.extensions.pop-shell.active-hint
      value: "false"
    - key: org.gnome.shell.extensions.pop-shell.gap-inner
      value: "uint32 0"
    - key: org.gnome.shell.extensions.pop-shell.gap-outer
      value: "uint32 0"
    - key: org.gnome.shell.extensions.pop-shell.show-title
      value: "false"
    - key: org.gnome.shell.extensions.pop-shell.tile-by-default
      value: "true"

- name: dconf
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    # clipboard-history extension settings
    - key: "/org/gnome/shell/extensions/clipboard-history/paste-on-selection"
      value: "false"
    - key: "/org/gnome/shell/extensions/clipboard-history/toggle-menu"
      value: "['<Control>F9']"
    # tilix settings
    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/visible-name"
      value: "'Default'"
    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/use-custom-command"
      value: "true"
    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/custom-command"
      value: "'/usr/bin/fish'"
    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/use-system-font"
      value: "false"
    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/font"
      value: "'Fira Code weight=453 12'"
    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/background-transparency-percent"
      value: "15"
    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/scrollback-unlimited"
      value: "true"
    # gnome-clocks
    - key: "/org/gnome/clocks/world-clocks"
      value: "[{'location': <(uint32 2, <('San Francisco', 'KOAK', false, [(0.65832848982162007, -2.133408063190589)], [(0.65832848982162007, -2.133408063190589)])>)>}, {'location': <(uint32 2, <('Virginia Beach', 'KNTU', true, [(0.64264962119230173, -1.326944735652658)], [(0.64320489769382372, -1.3260659972808639)])>)>}, {'location': <(uint32 2, <('Alicante', 'LEAL', true, [(0.66817020948739825, -0.0095993108859688137)], [(0.66933376813982537, -0.0084357522335417531)])>)>}, {'location': <(uint32 2, <('Dublin', 'EIDW', false, [(0.93258759116453926, -0.1090830782496456)], [(0.93258759116453926, -0.1090830782496456)])>)>}, {'location': <(uint32 2, <('Istanbul', 'LTBA', true, [(0.71500322271810779, 0.50294571860079684)], [(0.71590981654476371, 0.505529765824837)])>)>}, {'location': <(uint32 2, <('Moscow', 'UUWW', true, [(0.97127572873484425, 0.65042604039431762)], [(0.97305983920281813, 0.65651530216830811)])>)>}, {'location': <(uint32 2, <('Dubai', 'OMDB', true, [(0.44069563612856821, 0.96574884695243146)], [(0.44073441734454749, 0.9648180105024653)])>)>}, {'location': <(uint32 2, <('Tbilisi', 'UGTB', true, [(0.72726416071336797, 0.78460791321873025)], [(0.72809319210806533, 0.78161661086702972)])>)>}]"

- name: setup aquaproj
  include_tasks: aqua.yml

- name: setup cloud cli wrappers
  include_tasks: cloud.yml

- name: create registry-mirrors wrapper
  template:
    src: registry-mirrors.j2
    dest: "/home/{{ user }}/.local/bin/registry-mirrors"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0750

- name: add dialout group to user
  become: yes
  user:
    name: frezbo
    append: yes
    groups:
      - dialout

- name: disable brltty udev service
  become: yes
  systemd:
    name: brltty-udev.service
    masked: yes
    state: stopped
