- name: Find mattermost latest release
  uri:
    url: https://api.github.com/repos/mattermost/desktop/releases/latest
    return_content: true
  register: mm_metadata

- name: Get mattermost local version
  shell: |
    grep -aB 1 '"description": "Mattermost"' /opt/Mattermost/resources/app.asar | sed '$d;s/"//g;s/,//g' | awk '{print $2}'
  register: mattermost_local_info
  ignore_errors: yes

- name: Set mattermost metadata
  set_fact:
    mattermost_remote_version: "{{ mm_metadata.json.tag_name }}"
    mattermost_local_version: "v{{ mattermost_local_info.stdout }}"

- name: Install Mattermost
  become: yes
  apt:
    deb: "https://github.com/mattermost/desktop/releases/download/{{ mattermost_remote_version }}/mattermost-desktop-{{ mattermost_remote_version | replace('v', '') }}-linux-amd64.deb"
  when: mattermost_local_version != mattermost_remote_version
