- name: Install powerline
  become: yes
  apt:
    name:
      - powerline
      - powerline-gitstatus
    state: latest
    update_cache: yes

- name: Local fonts directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "/home/{{ user }}/.local/share/fonts"

- name: Download powerline fonts
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - url: https://github.com/powerline/fonts/raw/master/SourceCodePro/Source%20Code%20Pro%20for%20Powerline.otf
      dest: "/home/{{ user }}/.local/share/fonts/Powerline.otf"

- name: Enable powerline fonts
  command:
    argv:
      - fc-cache
      - -f
      - "/home/{{ user }}/.local/share/fonts"
    creates: "/home/{{ user }}/.local/share/fonts/.uuid"
