- name: Create user systemd directory
  file:
    path: "/home/{{ user }}/.config/systemd/user"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: create syncthing systemd user service 
  template:
    src: syncthing.service.j2
    dest: "/home/{{ user }}/.config/systemd/user/syncthing.service"
  notify:
    - reload user scoped systemctl

- name: enable syncthing rootless service
  systemd:
    name: syncthing.service
    state: started
    enabled: true
    scope: user
