- name: reload user scoped systemctl
  systemd:
    daemon_reload: true
    scope: user

- name: restart docker
  become: yes
  systemd:
    name: docker.service
    state: restarted

- name: restart tlp
  become: yes
  systemd:
    name: tlp.service
    state: restarted

- name: restart NetworkManager
  become: yes
  systemd:
    name: NetworkManager.service
    state: restarted
